[dependencies]
base = "0.11.1"
account-identifier = "1.0.2"
encoding = "https://github.com/aviate-labs/encoding.mo#master"
account = "1.0.1"
sha2 = "0.0.4"
vector = "0.3.1"
map = "9.0.1"

[dev-dependencies]
test = "2.0.0"
bench = "1.0.0"